### PR TITLE
CD

### PR DESCRIPTION
**Pull request by DanielVoogsgerd**
This is a ~tracking branch~ PR for ~efforts in CI~ CD in Brane documentation

This is ~mostly~ already working, it compiles the mdbooks and code docs and hosts it on GH-pages.
The url in use right now is: [https://brane.vgsg.nl](https://brane.vgsg.nl)

To Do:

- [ ] ~Remove dead links~ Postponed, see #6 
- [ ] ~Enable linkcheck (Remove commit named: "Remove this commit")~ Postponed, see #6 
- [x] Set correct trigger for deploy. Probably push to branch main

Suggestions are welcome :)

### CODE REVIEW

**Comment by Lut99** [comment]
Looking good so far!

Can you make sure the final version works with `wiki.enablingpersonalizedinterventions.nl`? Then I'll ask Cees to move our current domain name.

Is it also possible to do something with a certificate? And how did you refer to the GH page ~ using a CNAME or something?

**Comment by DanielVoogsgerd** [comment]
The repo does not contain any links to my own domain, so there should be no problem in that regard, I think.

With regards to the domains. Every GH account has a GitHub.io subdomain. It is mentioned in the GH repo settings under the GH pages section. We only need to create a cname record to that domain and we should be good.

**Comment by Lut99** [comment]
Requested CNAME update. Merging already to get everything in-order.

**Comment by DanielVoogsgerd** [comment]
Unfortunately, the build failed with a problem we already fixed in Brane in the last wave of PRs, I think something is not up to date. I will check it out.

**Pull request merged**
